version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks: [shared-net]

  pedido-ms:
    build:
      context: ./pedido-ms
      dockerfile: Dockerfile
    image: pedido-ms:1.0
    environment:
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/pedido_db"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on: [postgres, eureka-server]
    networks: [shared-net]

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:1.0
    ports:
      - "8761:8761"
    networks: [shared-net]

  composite-pedido:
    build:
      context: ./CompositionPedido
      dockerfile: Dockerfile
    image: composite-pedido:1.0
    environment:
      SERVER_PORT: "8088"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
    depends_on:
      - eureka-server
      - pedido-ms
    ports:
      - "8088:8088"
    networks: [ shared-net ]

networks:
  shared-net: { driver: bridge }
