spring:
  application:
    name: stock-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stock_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT:8095}
